### ISSUE TITLE
Automatically install pptrees.so into /usr/local/share/yosys/plugins if available

### ISSUE THREAD

**Issue by tdene** [lnis-uofu/yosys_prefix_trees#11]
This will bring back functionality that was previously removed, as I was not aware of the `-i` flag.

**Comment by mithro** [comment]
I think you probably want to use `pkg-config` to detect the Yosys install's plugin storage location?

**Comment by mithro** [comment]
I think this is done in https://github.com/chipsalliance/yosys-f4pga-plugins/blob/main/Makefile_plugin.common ?

**Comment by mithro** [comment]
Maybe @mkurc-ant can help?
