### ISSUE TITLE
Makefile method for setting YOSYS_CONFIG is not general?

### ISSUE THREAD

**Issue by tcal-x** [lnis-uofu/yosys_prefix_trees#9]
Currently in the Makefile:
```
YOSYS_PATH := $(realpath $(HOME)/data/yosys)
export YOSYS_CONFIG := $(YOSYS_PATH)/yosys-config
```

Is `$(HOME)/data/yosys` a path set up by Python / pip3 somehow?   In any case, it is not working for me when I do `make build`.

I think I recall another Makefile doing a `which yosys` and then using that to find `yosys-config`.

BTW I'm using a source-built yosys and a system install, so my yosys is at `/usr/local/bin/yosys`.

**Comment by tdene** [comment]
This is a hard-coded path.<br>
The repository should absolutely not include such hard-coded paths.

Will be fixed by v1.0, ETA 2022-04-15
